name = "Conda"
uuid = "8f4d0f93-b110-5947-807f-2305c1781a2d"
version = "1.5.0"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
VersionParsing = "81def892-9a0e-5fdd-b105-ffc91e053289"

[compat]
julia = "1"
JSON = "0.18,0.19,0.20,0.21"
VersionParsing = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
